#ifndef QTNETCOREENGINE_GLOBAL_H
#define QTNETCOREENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTNETCOREENGINE_LIBRARY)
#  define QTNETCOREENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTNETCOREENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTNETCOREENGINE_GLOBAL_H
