DEFINES += TARGET_RUNTIME_ID win7-x64
DEFINES += HOST_PKG_VER 1.1.0
DEFINES += HOST_POLICY_PKG_NAME runtime.win7-x64.Microsoft.NETCore.DotNetHostPolicy
DEFINES += HOST_POLICY_PKG_VER 1.1.0
DEFINES += HOST_POLICY_PKG_REL_DIR runtimes/win7-x64/native
DEFINES += REPO_COMMIT_HASH 9999

DEFINES += _NO_ASYNCRTIMP
DEFINES += _NO_PPLXIMP
DEFINES += COREHOST_MAKE_DLL 1
